### ISSUE TITLE
clusterm panic - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vvb** [contiv/cluster#64]
Noticed the following panic. clusterm was left over-night.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4ba606]
goroutine 55 [running]:
github.com/contiv/cluster/management/src/clusterm/manager.(*nodeDiscovered).process(0xc8202ea3e0, 0x0, 0x0)
    /go/src/github.com/contiv/cluster/management/src/clusterm/manager/events.go:47 +0x176
github.com/contiv/cluster/management/src/clusterm/manager.(*Manager).eventLoop(0xc820158190)
    /go/src/github.com/contiv/cluster/management/src/clusterm/manager/events.go:509 +0x15a
    created by github.com/contiv/cluster/management/src/clusterm/manager.(*Manager).Run
    /go/src/github.com/contiv/cluster/management/src/clusterm/manager/manager.go:128 +0x91

```

complete log at https://gist.github.com/vvb/52398d6a36b78c1fe2fa

**Comment by rkharya** [comment]
Seeing clusterm panic again on aci-scale setup, this time no activity was being performed on the setup, after successfully cluster formation nodes were left idle overnight - 

Apr 13 10:13:02 contiv-aci-scale-1.cisco.com clusterm[41042]: level=info msg="asset already in status: \"Allocated\" and state: \"Discovered\", no action required"
Apr 13 12:42:44 contiv-aci-scale-1.cisco.com clusterm[41042]: level=info msg="Event received: {Event:member-failed Members:[{Name:ucsb-blade2 Addr:10.193.231.88 Port:7946 Tags:map[NodeLabel:ucsb-blade2 NodeSerial:FCH1844JSV6 NodeAddr:10.193.231.88] Status:failed ProtocolMin:1 ProtocolMax:2 ProtocolCur:2 DelegateMin:2 DelegateMax:4 DelegateCur:4}]}"
Apr 13 12:42:44 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="monitor event: {Type:Disappeared Node:0xc82017b440}"
Apr 13 12:42:44 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="processing monitor event: {Type:Disappeared Node:0xc82017b440}"
Apr 13 12:42:44 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="enqueued manager event: nodeDisappeared: &{label:ucsb-blade2 serial:FCH1844JSV6 addr:10.193.231.88
[clusterctl-0413.txt](https://github.com/contiv/cluster/files/218664/clusterctl-0413.txt)
}"
Apr 13 12:42:44 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="dequeued manager event: nodeDisappeared: &{label:ucsb-blade2 serial:FCH1844JSV6 addr:10.193.231.88}"
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: level=info msg="Event received: {Event:member-join Members:[{Name:ucsb-blade2 Addr:10.193.231.88 Port:7946 Tags:map[NodeLabel:ucsb-blade2 NodeSerial:FCH1844JSV6 NodeAddr:10.193.231.88] Status:alive ProtocolMin:1 ProtocolMax:2 ProtocolCur:2 DelegateMin:2 DelegateMax:4 DelegateCur:4}]}"
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="monitor event: {Type:Discovered Node:0xc820304fc0}"
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="processing monitor event: {Type:Discovered Node:0xc820304fc0}"
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="enqueued manager event: nodeDiscovered: &{label:ucsb-blade2 serial:FCH1844JSV6 addr:10.193.231.88}"
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: level=debug msg="dequeued manager event: nodeDiscovered: &{label:ucsb-blade2 serial:FCH1844JSV6 addr:10.193.231.88}"
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: [signal 0xb code=0x1 addr=0x20 pc=0x4bc166]
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: goroutine 15 [running]:
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: panic(0x9b7180, 0xc82000e070)
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: /usr/local/go/src/runtime/panic.go:464 +0x3e6
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: github.com/contiv/cluster/management/src/clusterm/manager.(*nodeDiscovered).process(0xc82035a380, 0x0, 0x0)
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: /go/src/github.com/contiv/cluster/management/src/clusterm/manager/events.go:48 +0x176
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: github.com/contiv/cluster/management/src/clusterm/manager.(*Manager).eventLoop(0xc8201a2190)
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: /go/src/github.com/contiv/cluster/management/src/clusterm/manager/events.go:559 +0x146
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: created by github.com/contiv/cluster/management/src/clusterm/manager.(*Manager).Run
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com clusterm[41042]: /go/src/github.com/contiv/cluster/management/src/clusterm/manager/manager.go:127 +0x91
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com systemd[1]: clusterm.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com systemd[1]: Unit clusterm.service entered failed state.
Apr 13 12:45:12 contiv-aci-scale-1.cisco.com systemd[1]: clusterm.service failed.
Apr 13 12:45:22 contiv-aci-scale-1.cisco.com systemd[1]: clusterm.service holdoff time over, scheduling restart.
Apr 13 12:45:22 contiv-aci-scale-1.cisco.com systemd[1]: Started Clusterm.
-- Subject: Unit clusterm.service has finished start-up
-- Defined-By: systemd

After this few of the nodes are reported as un-allocated though they are part of the cluster. UCP reports them to be part of cluster -

"status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-2-FCH1924V2EK",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-3-FCH1924V2F0",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-4-FCH1924V2FP",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-5-FCH1924V2FA",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-6-FCH1924V2F6",
            "status": "Unallocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-7-FCH1924V2FC",
            "status": "Allocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-8-FCH1925V06J",
            "status": "Allocated",
            "prev-status": "Incomplete",
            "inventory-name": "contiv-aci-scale-9-FCH1924V2EZ",

In case issue is not related to Collins, attaching full clusterm logs herewith.
