### ISSUE TITLE
Vagrant Setup Fails

### ISSUE THREAD

**Issue by danehans** [contiv/cluster#95]
I am unable to deploy cluster manager using the the vagrant installation guide [1]. Here are the issues I have observed:

1. The guide uses ```make build``` to create a cluster manager dev environment. Behind the scenes, ```make build``` uses Docker to pull an image, etc.. Therefore you must install Docker on Mac OSX. According to Docker Mac OSX installation directions [2], you do not run Docker Engine directly on the OSX host. Instead, you install docker-tools, which uses docker-machine to run Docker Engine on a VM.

2. As a workaround, I tried running make demo from the project root dir. The deployment failed as follows:

```
dane-mac2:cluster daneyonhansen$ make demo
CONTIV_NODES=${CONTIV_NODES:-3} vagrant destroy -f
==> cluster-node1: VM not created. Moving on...
==> cluster-node2: VM not created. Moving on...
==> cluster-node3: VM not created. Moving on...
CONTIV_NODES=${CONTIV_NODES:-3} CONTIV_SRV_INIT=1 vagrant up
Bringing machine 'cluster-node3' up with 'virtualbox' provider...
Bringing machine 'cluster-node2' up with 'virtualbox' provider...
Bringing machine 'cluster-node1' up with 'virtualbox' provider...
==> cluster-node3: Importing base box 'contiv/centos72'...
==> cluster-node3: Matching MAC address for NAT networking...
==> cluster-node3: Checking if box 'contiv/centos72' is up to date...
==> cluster-node3: Setting the name of the VM: cluster_cluster-node3_1461115977129_72214
==> cluster-node3: Clearing any previously set network interfaces...
==> cluster-node3: Preparing network interfaces based on configuration...
    cluster-node3: Adapter 1: nat
    cluster-node3: Adapter 2: intnet
    cluster-node3: Adapter 3: intnet
==> cluster-node3: Forwarding ports...
    cluster-node3: 22 (guest) => 2222 (host) (adapter 1)
==> cluster-node3: Running 'pre-boot' VM customizations...
==> cluster-node3: Booting VM...
==> cluster-node3: Waiting for machine to boot. This may take a few minutes...
    cluster-node3: SSH address: 127.0.0.1:2222
    cluster-node3: SSH username: vagrant
    cluster-node3: SSH auth method: private key
    cluster-node3: Warning: Remote connection disconnect. Retrying...
==> cluster-node3: Forcing shutdown of VM...
==> cluster-node3: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_chdir.rb:25:in `chdir': Too many open files - getcwd (Errno::EMFILE)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_chdir.rb:25:in `block in safe_chdir'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_chdir.rb:24:in `synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_chdir.rb:24:in `safe_chdir'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/subprocess.rb:121:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/subprocess.rb:22:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/driver/base.rb:430:in `block in raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/driver/base.rb:429:in `raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/driver/base.rb:367:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/driver/base.rb:362:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/driver/version_5_0.rb:548:in `read_state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/provider.rb:97:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/wait_for_communicator.rb:26:in `block in call'
make: *** [start] Error 1
```

Aside from Docker, I am running all the required software and versions identified in the cluster manager vagrant deployment guide.

I receive the same error with CONTIV_NODES=3. I rebooted my laptop and tried the same steps, but I receive the same error.

[1] https://github.com/contiv/cluster/tree/master/management
[2] https://docs.docker.com/engine/installation/mac/

**Comment by vvb** [comment]
@danehans what version of vagrant are you running? Can you try things mentioned in https://github.com/mitchellh/vagrant/issues/2435

**Comment by danehans** [comment]
setting ```ulimit -n 4048``` on OSX got me past this issue. Thanks @vvb for your help.
